# Generated by Django 5.2.8 on 2025-12-09 22:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import smart_selects.db_fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre Producto')),
                ('desc', models.TextField(verbose_name='Descripción')),
                ('expdate', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Imagen de Producto')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Es Oferta?')),
                ('sale_price', models.IntegerField(default=0, verbose_name='Precio Oferta')),
            ],
        ),
        migrations.CreateModel(
            name='productState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Estado : ')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre de la Región')),
            ],
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Categoria de Tienda')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('categorycode', models.TextField(verbose_name='Codigo de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TestCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=19, unique=True)),
                ('expirydate', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=4)),
                ('scenario', models.CharField(choices=[('success', 'Pago Exitoso'), ('insufficient_funds', 'Fondos Insuficientes'), ('invalid_card', 'Tarjeta Inválida'), ('expired_card', 'Tarjeta Vencida'), ('declined', 'Pago Rechazado'), ('processing_error', 'Error de Procesamiento')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('total', models.IntegerField()),
                ('paymentStatus', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('paymentMethod', models.CharField(default='Tarjeta de Credito', max_length=50)),
                ('paymentScenario', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('isPicked', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.productstate', verbose_name='Estado del Producto:'),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre de la Provincia')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.region', verbose_name='Región a la que Pertenece')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre de la Comuna')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.province', verbose_name='Provincia a la que Pertenece')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Razón Social')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('ownername', models.TextField(verbose_name='Representante Legal')),
                ('rutowner', models.CharField(max_length=12, verbose_name='RUT Representante Legal')),
                ('openhr', models.TimeField(verbose_name='Hora de apertura')),
                ('closehr', models.TimeField(verbose_name='Hora de cierre')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('gps', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.province', verbose_name='Provincia')),
                ('state', smart_selects.db_fields.ChainedForeignKey(chained_field='province', chained_model_field='province', on_delete=django.db.models.deletion.CASCADE, to='Store.state', verbose_name='Comuna')),
                ('storetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.storetype', verbose_name='Tipo de Tienda')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store', verbose_name='Tienda'),
        ),
    ]
