# Generated by Django 5.2.8 on 2025-12-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='roman',
            field=models.TextField(default='X', verbose_name='Número Romano de la Región'),
            preserve_default=False,
        ),
    ]
