# Generated by Django 5.2.8 on 2025-12-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_region_roman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='province',
        ),
        migrations.RemoveField(
            model_name='store',
            name='province',
        ),
        migrations.AddField(
            model_name='state',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Store.region', verbose_name='Region a la que Pertenece'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='Region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Store.region', verbose_name='Región'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
