# Generated by Django 5.2.8 on 2025-12-09 22:43

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_remove_state_province_remove_store_province_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Region',
            new_name='region',
        ),
        migrations.AddField(
            model_name='store',
            name='emailowner',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Representante Legal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='Store.state', verbose_name='Comuna'),
        ),
    ]
