# Generated by Django 5.2.8 on 2025-12-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_rename_region_store_region_store_emailowner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='store',
            name='rut',
            field=models.CharField(max_length=12, verbose_name='RUT Razón Social'),
        ),
    ]
