# Generated by Django 5.2.8 on 2025-12-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_store_phone_alter_store_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='ownerlastname',
            field=models.TextField(blank=True, null=True, verbose_name='Apellido Representante Legal'),
        ),
        migrations.AlterField(
            model_name='store',
            name='ownername',
            field=models.TextField(verbose_name='Nombre Representante Legal'),
        ),
    ]
