# Generated by Django 5.2.8 on 2025-12-10 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_store_ownerlastname_alter_store_ownername'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='Store_order_created_3aae63_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paymentStatus'], name='Store_order_payment_9a43c5_idx'),
        ),
    ]
