# Generated by Django 5.2.8 on 2025-12-09 22:01

import django.contrib.auth.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('desc', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('lastname', models.TextField(verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.TextField(verbose_name='Contraseña')),
                ('userlocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='')),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.usertype', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
